### ISSUE TITLE
Making it open for everyone

### ISSUE THREAD

**Issue by Shishir47** [QKnot/NUBTK-Cover-Page-Generator#1]
Great idea. But don't limit this amazing thing to Intra-University. Instead, open it for everyone, and share it with them, people will get great help. Creating cover pages usually takes a lot of time but this can be a game changer! Best of luck!

**Comment by QKnot** [comment]
Thank you Vai for your encouragement! I'm glad you see the potential in this tool. Expanding it beyond the university is definitely something I’ll consider, as I want to make the process of creating cover pages easier for everyone. Your support means a lot.

**Comment by Shishir47** [comment]
Glad to hear that! Best of luck for future projects!
